stages:
  - build

variables:
  DOCKER_DRIVER: overlay2

build-backend:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd backend
    - docker build -t backend:$CI_COMMIT_SHA .
    - docker images | grep my-backend