stages:
  - test

show-vars:
  stage: test
  script:
    - 'echo "Commit SHA: $CI_COMMIT_SHA"'
    - 'echo "Branch: $CI_COMMIT_BRANCH"'
    - 'echo "Project: $CI_PROJECT_NAME"'
    - 'echo "Pipeline ID: $CI_PIPELINE_ID"'