"""yet another changes

Revision ID: 94402f5f37f8
Revises: 354302bda0d1
Create Date: 2026-03-05 11:34:45.197483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94402f5f37f8'
down_revision: Union[str, Sequence[str], None] = '354302bda0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Instrument_Measurement_ID'), 'Instrument_Measurement', ['ID'], unique=False)
    op.create_unique_constraint(None, 'Instrument_Measurement', ['Serial_Number'])
    op.create_index(op.f('ix_Reference_Instrument_Measurement_ID'), 'Reference_Instrument_Measurement', ['ID'], unique=False)
    op.create_unique_constraint(None, 'Reference_Instrument_Measurement', ['Serial_Number'])
    op.create_index(op.f('ix_Result_Verification_ID'), 'Result_Verification', ['ID'], unique=False)
    op.create_index(op.f('ix_Test_Tool_Verification_ID'), 'Test_Tool_Verification', ['ID'], unique=False)
    op.create_index(op.f('ix_Test_tool_ID'), 'Test_tool', ['ID'], unique=False)
    op.create_unique_constraint(None, 'Test_tool', ['Serial_Number'])
    op.create_index(op.f('ix_Testing_Instrument_ID'), 'Testing_Instrument', ['ID'], unique=False)
    op.create_index(op.f('ix_Type_Instrument_Measurement_ID'), 'Type_Instrument_Measurement', ['ID'], unique=False)
    op.create_index(op.f('ix_Type_Verification_ID'), 'Type_Verification', ['ID'], unique=False)
    op.create_index(op.f('ix_User_ID'), 'User', ['ID'], unique=False)
    op.create_unique_constraint(None, 'User', ['Login'])
    op.alter_column('Verification', 'Real_Date_Verification',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('Verification', 'Valid_Until',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_index(op.f('ix_Verification_ID'), 'Verification', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Verification_ID'), table_name='Verification')
    op.alter_column('Verification', 'Valid_Until',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('Verification', 'Real_Date_Verification',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_index(op.f('ix_User_ID'), table_name='User')
    op.drop_index(op.f('ix_Type_Verification_ID'), table_name='Type_Verification')
    op.drop_index(op.f('ix_Type_Instrument_Measurement_ID'), table_name='Type_Instrument_Measurement')
    op.drop_index(op.f('ix_Testing_Instrument_ID'), table_name='Testing_Instrument')
    op.drop_constraint(None, 'Test_tool', type_='unique')
    op.drop_index(op.f('ix_Test_tool_ID'), table_name='Test_tool')
    op.drop_index(op.f('ix_Test_Tool_Verification_ID'), table_name='Test_Tool_Verification')
    op.drop_index(op.f('ix_Result_Verification_ID'), table_name='Result_Verification')
    op.drop_constraint(None, 'Reference_Instrument_Measurement', type_='unique')
    op.drop_index(op.f('ix_Reference_Instrument_Measurement_ID'), table_name='Reference_Instrument_Measurement')
    op.drop_constraint(None, 'Instrument_Measurement', type_='unique')
    op.drop_index(op.f('ix_Instrument_Measurement_ID'), table_name='Instrument_Measurement')
    # ### end Alembic commands ###
