"""another migration

Revision ID: 99e1d7801eb1
Revises: 
Create Date: 2026-03-15 21:27:22.830160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e1d7801eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reference_Instrument_Measurement',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Serial_Number', sa.String(), nullable=False),
    sa.Column('Date_Admission', sa.Date(), nullable=False),
    sa.Column('Valid_For', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Serial_Number')
    )
    op.create_index(op.f('ix_Reference_Instrument_Measurement_ID'), 'Reference_Instrument_Measurement', ['ID'], unique=False)
    op.create_table('Result_Verification',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Result_Name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Result_Verification_ID'), 'Result_Verification', ['ID'], unique=False)
    op.create_table('Test_tool',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Serial_Number', sa.String(), nullable=False),
    sa.Column('Active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Serial_Number')
    )
    op.create_index(op.f('ix_Test_tool_ID'), 'Test_tool', ['ID'], unique=False)
    op.create_table('Type_Instrument_Measurement',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name_Company', sa.String(), nullable=False),
    sa.Column('Batch_Number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Type_Instrument_Measurement_ID'), 'Type_Instrument_Measurement', ['ID'], unique=False)
    op.create_table('Type_Verification',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Type_Name', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Type_Verification_ID'), 'Type_Verification', ['ID'], unique=False)
    op.create_table('User',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Surname', sa.String(length=100), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Patronymic', sa.String(length=100), nullable=True),
    sa.Column('Login', sa.String(length=100), nullable=False),
    sa.Column('Hashed_Password', sa.String(length=100), nullable=False),
    sa.Column('Admin_Role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Login')
    )
    op.create_index(op.f('ix_User_ID'), 'User', ['ID'], unique=False)
    op.create_table('Instrument_Measurement',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Serial_Number', sa.String(), nullable=False),
    sa.Column('Date_Admission', sa.Date(), nullable=False),
    sa.Column('ID_Type_Instrument', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Type_Instrument'], ['Type_Instrument_Measurement.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Serial_Number')
    )
    op.create_index(op.f('ix_Instrument_Measurement_ID'), 'Instrument_Measurement', ['ID'], unique=False)
    op.create_table('Verification',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Planned_Date_Verification', sa.Date(), nullable=False),
    sa.Column('Date_Receipt', sa.Date(), nullable=False),
    sa.Column('Temperature', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Pressure', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('Wetness', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('Complete_Electric_test', sa.Boolean(), nullable=True),
    sa.Column('Complete_Voltage_test', sa.Boolean(), nullable=True),
    sa.Column('Complete_Isolation_test', sa.Boolean(), nullable=True),
    sa.Column('ID_Result', sa.Integer(), nullable=True),
    sa.Column('Real_Date_Verification', sa.Date(), nullable=True),
    sa.Column('Valid_Until', sa.Date(), nullable=True),
    sa.Column('ID_Type', sa.Integer(), nullable=True),
    sa.Column('ID_Metrologist', sa.Integer(), nullable=True),
    sa.Column('ID_Instrument', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Instrument'], ['Instrument_Measurement.ID'], ),
    sa.ForeignKeyConstraint(['ID_Metrologist'], ['User.ID'], ),
    sa.ForeignKeyConstraint(['ID_Result'], ['Result_Verification.ID'], ),
    sa.ForeignKeyConstraint(['ID_Type'], ['Type_Verification.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Verification_ID'), 'Verification', ['ID'], unique=False)
    op.create_table('Test_Tool_Verification',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_Verification', sa.Integer(), nullable=False),
    sa.Column('ID_Test_Tool', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Test_Tool'], ['Test_tool.ID'], ),
    sa.ForeignKeyConstraint(['ID_Verification'], ['Verification.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Test_Tool_Verification_ID'), 'Test_Tool_Verification', ['ID'], unique=False)
    op.create_table('Testing_Instrument',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('ID_Verification', sa.Integer(), nullable=False),
    sa.Column('ID_Reference_Instrument', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Reference_Instrument'], ['Reference_Instrument_Measurement.ID'], ),
    sa.ForeignKeyConstraint(['ID_Verification'], ['Verification.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Testing_Instrument_ID'), 'Testing_Instrument', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Testing_Instrument_ID'), table_name='Testing_Instrument')
    op.drop_table('Testing_Instrument')
    op.drop_index(op.f('ix_Test_Tool_Verification_ID'), table_name='Test_Tool_Verification')
    op.drop_table('Test_Tool_Verification')
    op.drop_index(op.f('ix_Verification_ID'), table_name='Verification')
    op.drop_table('Verification')
    op.drop_index(op.f('ix_Instrument_Measurement_ID'), table_name='Instrument_Measurement')
    op.drop_table('Instrument_Measurement')
    op.drop_index(op.f('ix_User_ID'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Type_Verification_ID'), table_name='Type_Verification')
    op.drop_table('Type_Verification')
    op.drop_index(op.f('ix_Type_Instrument_Measurement_ID'), table_name='Type_Instrument_Measurement')
    op.drop_table('Type_Instrument_Measurement')
    op.drop_index(op.f('ix_Test_tool_ID'), table_name='Test_tool')
    op.drop_table('Test_tool')
    op.drop_index(op.f('ix_Result_Verification_ID'), table_name='Result_Verification')
    op.drop_table('Result_Verification')
    op.drop_index(op.f('ix_Reference_Instrument_Measurement_ID'), table_name='Reference_Instrument_Measurement')
    op.drop_table('Reference_Instrument_Measurement')
    # ### end Alembic commands ###
