name: Test Workflow

on:
    push:
        branches:
            - master
    pull_request:
        branches: [ master ]

jobs: 
    test:
        runs-on: ubuntu-latest
 
        steps:
          - uses: actions/checkout@v6

          - name: show vars
            run: |
                echo "Commit SHA: ${{ github.sha }}"
                echo "Branch: ${{ github.ref_name }}"
                echo "Repository: ${{ github.repository }}"
                echo "Run ID: ${{ github.run_id }}"

          - name: cache pip requirements
            uses: actions/cache@v5
            with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

          - name: Cache npm packages
            uses: actions/cache@v3
            with:
                path: frontend/node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        
          - name: build-backend
            run: |
                cd backend/
                docker build -t back:${{ github.sha }} .
                docker images | grep back
          
          - name: build-frontend
            run: |
                cd frontend
                docker build -t front:${{ github.sha }} .
                docker images | grep front