name: Test Workflow

on:
    push:
        branches:
            - master
    pull_request:
        branches: [ master ]

jobs: 
    cache:
        runs-on: ubuntu-latest
 
        steps:
          - uses: actions/checkout@v6

          - name: cache pip requirements
            uses: actions/cache@v5
            with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}

          - name: Cache npm packages
            uses: actions/cache@v5
            with:
                path: frontend/node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

    test:
        runs-on: ubuntu-latest
        needs: cache

        steps:
          - uses: actions/checkout@v6

          - name: pytest
            run: |
                cd backend/
                pip install pytest fastapi sqlalchemy httpx
                pytest
        
    backend:
        runs-on: ubuntu-latest
        needs: [ cache, test ]

        steps:
          - uses: actions/checkout@v6
          - name: build-backend
            run: |
                cd backend/
                docker build -t back:${{ github.sha }} .
                docker images | grep back
          
    frontend:
        runs-on: ubuntu-latest
        needs: cache

        steps:
          - uses: actions/checkout@v6
          - name: build-frontend
            run: |
                cd frontend/
                docker build -t front:${{ github.sha }} .
                docker images | grep front